# Generated by Django 4.2.7 on 2023-11-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_exerciseinstance_hours_and_more'),
    ]

    operations = [
    ]
