# Generated by Django 4.2.7 on 2023-11-12 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231111_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 4, 35, 24, 799596, tzinfo=datetime.timezone.utc)),
        ),
    ]
