# Generated by Django 4.2.7 on 2023-11-12 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exerciseinstance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 21, 13, 37, 448971, tzinfo=datetime.timezone.utc)),
        ),
    ]
