# Generated by Django 4.2.7 on 2023-11-12 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_food_date_alter_exerciseinstance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 12, 21, 14, 34, 85196, tzinfo=datetime.timezone.utc)),
        ),
    ]
