# Generated by Django 4.2.7 on 2023-11-12 21:3
from datetime import timedelta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_exerciseinstance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintsance',
            name='calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='date',
            field=models.IntegerField(default=1),
        ),
    ]
