# Generated by Django 4.2.7 on 2023-11-12 21:52

from django.db import migrations, models
import django.utils.timezone
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_foodintsance_calories_alter_exerciseinstance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinstance',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='date',
            field=models.IntegerField(default=1),
        ),
    ]
