# Generated by Django 4.2.7 on 2023-11-12 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_exerciseinstance_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='duration',
            field=models.DurationField(),
        ),
    ]
