# Generated by Django 4.2.7 on 2023-11-12 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_exerciseinstance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintsance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
