# Generated by Django 4.2.7 on 2023-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeruser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
